name: Trigger auto deployment for container-app-mnssiatdccwwe

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/container-app-mnssiatdccwwe-AutoDeployTrigger-13c18512-5b56-4677-b42d-0137f868bc6a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPMNSSIATDCCWWE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMNSSIATDCCWWE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMNSSIATDCCWWE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrymnssiatdccwwe.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPMNSSIATDCCWWE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMNSSIATDCCWWE_REGISTRY_PASSWORD }}
          containerAppName: container-app-mnssiatdccwwe
          resourceGroup: staticwebappsgallerycodesamples881c
          imageToBuild: containerregistrymnssiatdccwwe.azurecr.io/container-app-mnssiatdccwwe:${{ github.sha }}
          


